### ISSUE TITLE
Renaming of folders

### ISSUE THREAD

**Issue by peaveyman** [equeim/tremotesf2#10]
When I download music I always rename the folders to a certain format before I start the download. With this app I have to tell it to not start the download right away, then go into the file section to rename it the way I want it. Is it possible to add the rename to the first popup when tremotesf2 gets the torrent file?

**Comment by peaveyman** [comment]
Have you had a chance to look at this request?

**Comment by equeim** [comment]
Sorry for the late answer. It is possible to implement this. I will add this in 1.5 or 1.6.

**Comment by peaveyman** [comment]
Thanks

**Comment by peaveyman** [comment]
Is this fixed in 1.5.6

**Comment by peaveyman** [comment]
I am running the latest version and was wondering if you'd had a chance to look at this anymore.

**Comment by equeim** [comment]
Fixed in 1.7.0
