### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by alabotski** [equeim/tremotesf2#153]
Is it possible to add progress in the form of text to the progress indicator?

![image](https://user-images.githubusercontent.com/439337/187853272-4d58ee36-bdcc-4505-8889-55d4fc989868.png)

**Comment by mahkitah** [comment]
Yes, it's a waste of space to have 2 columns for this

**Comment by Teloriun** [comment]
Incorporating both would be good, or you could take it further and have it similar to Kebler which also includes the torrent status which I feel look 'cleaner'?

eg.
![image](https://user-images.githubusercontent.com/13600266/205436489-34cd704e-9637-4767-8031-c096f2966f59.png)
