### ISSUE TITLE
new beta of transmission support?

### ISSUE THREAD

**Issue by rezad1393** [equeim/tremotesf2#214]
it has been released 8 days ago.
https://github.com/transmission/transmission/releases/tag/4.0.0-beta.1

there is this:
"The remote control GUIs (transmission-qt and transmission-web) now use the RPC API "table" mode, resulting in smaller payloads / less bandwidth use."

is there any plan to for support of this new version?

**Comment by equeim** [comment]
As far as I understand, both mode are supported in transmission-daemon. This changelog entry just mentions that official RPC clients switched to the new one. Tremotesf will continue to work using old mode (which is default).

Although adding support of table would be a good idea of course.
