### ISSUE TITLE
Version pre 2 for ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by dawez** [equeim/tremotesf2#244]
Is there a version of `tremotesf` somewhere that runs on mint 20.3 (based on Ubuntu 20.04 LTS)?  I remember that once there was a package but not it seems that it was removed. It is available anywhere?

Version 2 needs some libraries that are not available on Ubuntu 20.04.

**Comment by boozyy** [comment]
Getting a connection error on Ubuntu Ubuntu 22.04.1 LTS x86_64

**Comment by equeim** [comment]
I added back 1.11.3 build for 20.04 on OBS - https://build.opensuse.org/package/show/home:equeim:tremotesf/Tremotesf_1x
Follow same instructions to add repo as in README, just replace 22.04 with 20.04

**Comment by dawez** [comment]
Ok perfect, thanks!

I just used the follow to install on ubuntu 20.04 in case someone needs a quick copy & paste:

```bash
wget -qO - https://download.opensuse.org/repositories/home:/equeim:/tremotesf/xUbuntu_20.04/Release.key | sudo tee /etc/apt/trusted.gpg.d/tremotesf.asc
sudo add-apt-repository "deb http://download.opensuse.org/repositories/home:/equeim:/tremotesf/xUbuntu_20.04/ /"
sudo apt update
sudo apt install tremotesf
```

**Comment by dawez** [comment]
Closing this issue as the resource is now available.
