### ISSUE TITLE
Adding trackers to an existing distribution.

### ISSUE THREAD

**Issue by Adler-lug** [equeim/tremotesf2#249]
There is one useful feature missing, which is in Transmission Remote GUI, when when trying to add a torrent file that is already on the distribution, it was suggested to add trackers.

**Comment by peelos** [comment]
this works for me

![image](https://user-images.githubusercontent.com/22773041/208054322-969bb3fc-c549-471a-b65a-328b0093671d.png)

**Comment by thany** [comment]
@peelos This is not working. I don't know how you got it working.

For a torrent file (or magnet) that definitely includes more trackers than the identical existing torrent already added priorly, it does NOT attempt to merge new trackers. It just bluntly says the torrent is already added and leaves it at that.

![image](https://github.com/equeim/tremotesf2/assets/152227/d2657104-5f7f-4005-9fbd-0ee6ce6033eb)

**Comment by equeim** [comment]
Done in 2.7.0
