### ISSUE TITLE
GPG keys expired

### ISSUE THREAD

**Issue by davewongillies** [equeim/tremotesf2#26]
Looks like the [GPG keys](https://build.opensuse.org/project/keys_and_certificates/home:equeim:tremotesf) used for building packages have expired

```
Fingerprint: 374d 7549 7a38 afc4 8f60 2684 c26e 78ba 0be2 2d96
Key: ID c26e78ba0be22d96
Expires on: 2020-10-22
```

**Comment by equeim** [comment]
Should be fixed.
