### ISSUE TITLE
Torrent list row size changes after adding new column and forgotten on restart

### ISSUE THREAD

**Issue by fiasko** [equeim/tremotesf2#304]
When I add an "Added On" column to torrent list, the row size changes. This might be some sort of issue to take account the display scaling after column change.
Another thing linked to this the UI layout and sorting settings are not saved. They always reset back to default on restart.

**Comment by equeim** [comment]
What OS do you run Tremotesf on?

**Comment by fiasko** [comment]
On Windows 11. But I haven't seen the issue with Tremotesf 2.2.0 and 2.3.0 anymore. So maybe it's already fixed.
