### ISSUE TITLE
Error selecting directory

### ISSUE THREAD

**Issue by mikulik86** [equeim/tremotesf2#337]
Hello,

when selecting a Download directory I get the following Error: 
`Selected directory should be inside mounted directory`

Tremotesf running on windows machine, transmission-daemon running on linux server.
Linux mount point `/mnt/NAS` is mounted on Windows PC as `N:\`.

My settings look like this:
![image](https://github.com/equeim/tremotesf2/assets/39491786/8623d12a-29fd-4c0a-b4fe-40acdc3c7686)

Am I doing something wrong?

**Comment by equeim** [comment]
It should be other may around. Remote directory is the directory on a machine where Transmission is running (N:\ in your case), local directory is where it is mounted on a machine where Tremotesf is running (/mnt/NAS).

**Comment by mikulik86** [comment]
Like this not working either:
![image](https://github.com/equeim/tremotesf2/assets/39491786/bfb5754c-6660-4d9d-baed-19f9911e26d6)

Please help.

**Comment by mikulik86** [comment]
So in my case it works like this:
![image](https://github.com/equeim/tremotesf2/assets/39491786/f892a084-b1d8-461e-a309-d01c6f22698a)

The problem is, that it doesn't work with network drives. @equeim could you please fix it?

**Comment by mikulik86** [comment]
The slash was the problem. Like this it works.
![image](https://github.com/equeim/tremotesf2/assets/39491786/f6416d31-c757-4f97-a324-149ba30259cf)

The slash is added automatically when adding a directory with the "+ Add" button.
@equeim you may want to consider fixing it 😉

**Comment by Tharn** [comment]
It can also happen when having a network path in "Local" and inputting a Windows drive by hand in "Remote". I'm used to adding backslash, but this does not work. It should really parse backslash for Windows drives, as it's functionally identical whether it's added or not.

**Comment by Tharn** [comment]
Another directory issue so I'll add it right here:

Having two entries, such as, for example,
//192.168.0.1/D mounted to D:
//192.168.0.1/E mounted to E:

Will make opening the path fail, even though this mapping accounts for all torrents properly. Removing one of the two makes the other one work properly again.

**Comment by equeim** [comment]
It should hopefully be fixed in the latest version
