### ISSUE TITLE
Dark theme support?

### ISSUE THREAD

**Issue by Revenger** [equeim/tremotesf2#35]
Running Windows 11 in dark mode and noticed the program is light, would be cool it had a windows theme colour mode.

**Comment by equeim** [comment]
I don't think it is possible to properly implement this without significant effort.
First of all, Qt's native windows style doesn't support changing elements colors and doesn't integrate with dark theme at all. This means that we would need to switch to different style, e.g. Fusion, and it doesn't look as native.
The biggest problem is title bar. Native title bar that Windows draws for us doesn't have dark theme support either. We would need to reimplement it ourselves (that's what all other apps with dark theme support do too), and this is very non-trivial task, especially if we want it to not look out of place.

**Comment by rezad1393** [comment]
I have this program running in dark mode.
because I have breeze dark theme as kde theme.
it is ok.
but if you can add a alternating color/brightness to rows it would be way easier to use.

right now it is just one color.

**Comment by thany** [comment]
Nearly a year later, has this been resolved yet by any chance? Surely, Qt is themeable, which is proven when running it on Linux, innit. And surely, the team behind Qt knows that Windows can do dark mode since, what, 5 years ago? Surely, they have made efforts of _some_ description towards supporting this?

I just can't believe that a **UI toolkit** which is that popular, would not be themeable. Or its themability would be platform-dependent while it itself is a cross-platform toolkit. Just can't believe it.

**Comment by equeim** [comment]
>Or its themability would be platform-dependent while it itself is a cross-platform toolkit. Just can't believe it.

The main problem was that Windows had no way for Win32 apps to know whether system is in dark mode (without using undocumented hacks), and no way to enable dark theme window title (it was always drawn with white background). It seems that Microsoft finally added necessary APIs in Windows 11 though. I will see what I can do to support them.

It won't work on Windows 10 though (only manual theme switching with always white title bar will be available).

**Comment by rezad1393** [comment]
> > Or its themability would be platform-dependent while it itself is a cross-platform toolkit. Just can't believe it.
> 
> The main problem was that Windows had no way for Win32 apps to know whether system is in dark mode (without using undocumented hacks), and no way to enable dark theme window title (it was always drawn with white background). So that's on Microsoft. It seems that they finally added necessary APIs in Windows 11 though. I will see what I can do to support them.
> 
> It won't work on Windows 10 or 8.1 of course (only manual theme switching with always white title bar will be available).

lesson of the day:
use linux.

**Comment by thany** [comment]
> > Or its themability would be platform-dependent while it itself is a cross-platform toolkit. Just can't believe it.
> 
> The main problem was that Windows had no way for Win32 apps to know whether system is in dark mode (without using undocumented hacks), and no way to enable dark theme window title (it was always drawn with white background). So that's on Microsoft. It seems that they finally added necessary APIs in Windows 11 though. I will see what I can do to support them.
> 
> It won't work on Windows 10 or 8.1 of course (only manual theme switching with always white title bar will be available).

Lots of win32 (and win64 I guess) applications that can do dark mode. I need not remind you that even if an application cannot "see" the system setting for dark mode, it doesn't mean that dark mode has to be totally absent. There can still be a manual switch.

You can also look at it from the other side: how can you decide the application should be in **light** mode, when the system setting is unknown? It feels like dark mode is assumed to be "the odd one out", but to me it's the other way round.

**Comment by rezad1393** [comment]
> It's not that simple. For a thing that Linux cannot do but Windows can, one could easily argue the opposite. But unfortunately, no OS is universal enough to do absolutely everything perfectly. To each their own.

it was a joke.

I use linux and wayland is still way behind windows.
not fractional scaling, no comprehensive HDR and so on and on.

still using libre software is the way forward instead of proprietary  software.
I have no idea why after last two decade why would anyone that is informed, would use software that he is not in control of (or at least can see what is the source of  code that is running)

**Comment by thany** [comment]
Like I said, to each their own.

A discussion about OSes and opensource vs proprietary is better discussed elsewhere, will all due respect. This is issue was about dark mode:
* The supposed inability for a win64 application to detect it, which is disproved by several existing applications.
* The general lack of theme support in Qt, which seems disproved by it working perfectly fine in Linux.

Perhaps we can get back to the matter at hand, and figure out why it ain't working on Windows, and how to get it to work. So then, with that in mind, what are the options?

**Comment by rezad1393** [comment]
> Like I said, to each their own.
> 
> A discussion about OSes and opensource vs proprietary is better discussed elsewhere, will all due respect. This is issue was about dark mode:
> 
>     * The supposed inability for a win64 application to detect it, which is disproved by several existing applications.
> 
>     * The general lack of theme support in Qt, which seems disproved by it working perfectly fine in Linux.
> 
> 
> Perhaps we can get back to the matter at hand, and figure out why it ain't working on Windows, and how to get it to work. So then, with that in mind, what are the options?

sorry.
when I searched for dark theme for this app and found this issue, I didnt want to open another issue and followed it here.
I am a bit passionate about linux but it doesn't  excuse forcing other to convert.
I will unsubscribe from this issue.

**Comment by jkr442** [comment]
I just installed 2.6.2 and dark theme is working perfectly on Windows 11. Great work!
