### ISSUE TITLE
Feature request: force no proxy connection

### ISSUE THREAD

**Issue by uprprc777** [equeim/tremotesf2#368]
I am using the lastest 2.4.0 release Windows spp.
I want to disable proxy for tremotesf2 but I would need to enable proxy in the System settings for some other apps.
I tried to set the proxy to default in tremotesf2. With the system settings of proxy is on, tremotesf2 connect through the proxy. And there is no other option to disable proxy for tremotesf2.
Please add an option `disabled` for Tools > Connection Settings > Proxy > Proxy type.

**Comment by equeim** [comment]
Done in 2.7.0
