### ISSUE TITLE
Update refresh interval doesn't work

### ISSUE THREAD

**Issue by Revenger** [equeim/tremotesf2#369]
Having both this and Transmission Remote GUI up this program the update interval  time doesn't work as I set it to 1s and the only time the window updates is when it receives a user input mouse click on someting in the window, toolbar, button etc.

So the automatic refresh update backgroud timer isn't working and only refreshes the window when theres a active click on it.

Screenshot showing what I mean, update interval time was ok'd and window ewopened for the screeshot to be taken.
Even so with the progress diffrence showing in each window thats more than 10 seconds.
As of this edit its finished checking and downloading the updates to that file and this program is still showing 67.9% checking.
![Screenshot 2023-08-18 154520](https://github.com/equeim/tremotesf2/assets/597280/5d2a11e7-2e0c-4195-a5f4-3f2ddc6558f3)

**Comment by Revenger** [comment]
Still doing this on 2.6.3
Window update interval doesn't work and I could add a torrent let it sit and it would still show 0% downloaded if the window isn't clicked then suddenly it'll tell me its completed and jump to 100%.

**Comment by bassstorm** [comment]
Same here on KDE

**Comment by Tharn** [comment]
Can confirm on Windows 10. 1s interval, but GUI only updates progress / UL / DL when mouse is clicked on the item in question.

The UL / DL current on the status bar is updated properly at 1s inteval.

**Comment by Revenger** [comment]
2.7.2 still the same program isn't updating unless window is clicked.

**Comment by equeim** [comment]
Should be fixed in 2.7.3
