### ISSUE TITLE
official Debian package

### ISSUE THREAD

**Issue by anarcat** [equeim/tremotesf2#392]
Hi!

I'm working on making an official debian package for this. 

I published the sources of my work at:

https://salsa.debian.org/debian/tremotesf

It takes some of your `debian/` work, but improves on them to silence lintian warnings and make things work...

Work is tracked in http://bugs.debian.org/1053805 and the next step is to pass the "NEW" queue.

**Comment by barak** [comment]
The alternative I've been using is the Debian package `transmission-remote-gtk`, so it would be nice to see a comparison of the two in `debian/README.Debian` or even the package description, and also some quick instruction for transitioning: how to extract the relevant remote info from one of these clients, and where to copy it to in the other. (In my imagined computer utopia, the two programs would share a single configuration file for remote daemons, but that's just a fantasy.)

**Comment by anarcat** [comment]
The package has been accepted in Debian.

@barak I`m not sure what to do about your request... It would be rather impractical to make a thorough comparison of tremotesf with every other torrent (or transmission?) client out there, and I certainly don't think the package description is an apt place to do that. README.Debian maybe, but I already list the interesting features of tremotfs in the package description and explained the rationale to uploading this to Debian in the ITP bug... 

In any case, I think this can be closed... @equeim I think you can get rid of your `debian/` directory, we can maintain that on our side from here on... Thanks for doing most of the hard work for me! :)

**Comment by barak** [comment]
Just installed it and tried it out. Nice! I don't see much difference, in terms of user experience, from `transmission-remote-gtk`, but it does seem perhaps a bit faster. One minor difference is that `tremotesf` can only be configured for a single transmission server, while `transmission-remote-gtk` can be configured for multiple servers, although you can only connect to one at a time.

**Comment by equeim** [comment]
> One minor difference is that tremotesf can only be configured for a single transmission server, while transmission-remote-gtk can be configured for multiple servers, although you can only connect to one at a time.

You can add multiple servers and switch between them in "Connection settings" dialog (in "Tools" menu).

**Comment by equeim** [comment]
> In any case, I think this can be closed... @equeim I think you can get rid of your `debian/` directory, we can maintain that on our side from here on... Thanks for doing most of the hard work for me! :)

@anarcat I still need for CI purposes. I don't think I will remove OBS Debian repository just yet since presumably the official package won't be backported to bookworm and bullseye (correct me if I'm wrong). So I want to make sure that deb package can be built (i.e. that my `debian/` files are correct) before I upload new version to OBS. What do you think should be correct approach here? Debian build system is quite confusing in this regard.

**Comment by anarcat** [comment]
> I still need for CI purposes. I don't think I will remove OBS Debian
> repository just yet since presumably the official package won't be
> backported to bookworm and bullseye (correct me if I'm wrong).

We can *definitely* backport to bookworm. bullseye is a bit far and I
wouldn't personnally bother, but if you want to, we can!

> So I want to make sure that deb package can be built (i.e. that my `debian/` files are correct) before I upload new version to OBS. What do you think should be correct approach here? Debian build system is quite confusing in this regard.

A dilligent maintainer can upload a new package to unstable within a few
hours or days from the new upstream release. I have notifications on my
packages that come out approximatively daily, and I try to be dilligent
in following upstream in unstable.

We have CI too! It's not enabled for your package because it's not clear
to me what test suite should be ran on the installed package, but the
build-time test suite should be ran by the build server.

You can see the package dashboard here:

https://tracker.debian.org/pkg/tremotesf

There you can see the package is now waiting in unstable a bit (5 days)
before entering in testing. From there it can be legitimately uploaded
to bookworm and bullseye.

Happy to answer any other question you have about Debian! I know it's an
old and sometimes confusing environment, but it's not *that* bad. :)

**Comment by equeim** [comment]
> A dilligent maintainer can upload a new package to unstable within a few
hours or days from the new upstream release. I have notifications on my
packages that come out approximatively daily, and I try to be dilligent
in following upstream in unstable.

My concern is that I provide Debian repos on OBS (https://build.opensuse.org/package/show/home:equeim:tremotesf/Tremotesf) for 11/12/testing, and I don't want to drop them until official package is available in Debian stable at least. To be confident that I can make a new release and immediately publish it to OBS without surprises, I build deb package in GitHub Actions on each commit to master. I can't just remove `debian/` files from Git and use ones from official package instead, because they need to be aligned with my current master at the time of commit (e.g. in case I add a new dependency that needs to added to debian/control). Should I move them to separate Git repository instead?

**Comment by anarcat** [comment]
> My concern is that I provide Debian repos on OBS (https://build.opensuse.org/package/show/home:equeim:tremotesf/Tremotesf) for 11/12/testing, and I don't want to drop them until official package is available in Debian stable at least.

That makes sense! Give me a few days and that might just be reality. ;)

> To be confident that I can make a new release and immediately publish it to OBS without surprises, I build deb package in GitHub Actions on each commit to master.

Getting *that* to work in Debian would be a little bit trickier. You
actually made me think of this and realize that we *could* have our own
git repositories (salsa.debian.org) track yours and run CI on that. But
that's not currently the way things are done.

> I can't just remove `debian/` files from Git and use ones from official package instead, because they need to be aligned with my current master at the time of commit (e.g. in case I add a new dependency that needs to added to debian/control). Should I move them to separate Git repository instead?

Typically, they're on a separate branch. But really, you shouldn't worry
about this too much.

You *might* want to look at the changes I did on top of yours
though. Two ways:

https://salsa.debian.org/debian/tremotesf/-/tree/debian/sid/debian

https://sources.debian.org/src/tremotesf/2.5.0-1/
