### ISSUE TITLE
Please put the progress percentage inside the progress bar instead of next to it

### ISSUE THREAD

**Issue by Pentaphon** [equeim/tremotesf2#393]
What the title says. 2.5.0 only put it next to the bar.

**Comment by w108x** [comment]
it's funny because I was waiting for this change and when I saw the release notes I was like "yes! finally" only for it to look almost exactly like I had it before hehe... one day maybe

**Comment by bassstorm** [comment]
@equeim fair enough, hopefully you'll find time and desire one day :)
