### ISSUE TITLE
adding multiple magnet links 

### ISSUE THREAD

**Issue by rezad1393** [equeim/tremotesf2#397]
most apps (for example qbittorrent) support adding multiple magnets but I cant do that with this app.

**Comment by equeim** [comment]
You can kinda do it now by copying them and pressing ctrl-v in main window (or using drag&drop). Though I suppose it would be nice to make torrent link field in dialog multiline and able to handle multiple links.

**Comment by rezad1393** [comment]
most clients I saw supports this.

even webUI in qbittorrent supports this.

**Comment by equeim** [comment]
Done in 2.7.0
