### ISSUE TITLE
Authentication problem when username/password are empty

### ISSUE THREAD

**Issue by dawez** [equeim/tremotesf2#43]
I tried to login to a remote transmission server that has empty username/password set as authentication.

For example I can login with the browser just pressing enter on the auth dialogue. It seems that **tremotesf2** is not able to login on this server and I receive  "Authentication error".

Fragment of transmission server config:

```json
"rpc-authentication-required": true,
"rpc-password": "",
"rpc-port": 9091,
"rpc-url": "/transmission/",
"rpc-username": "",
``` 

Client setup:

![image](https://user-images.githubusercontent.com/2534771/142689647-5275d710-678b-4603-a1d0-69901843fd2c.png)

**Comment by dawez** [comment]
At the end there was an issue somewhere else in my config.

**Comment by equeim** [comment]
How did you fix this?
I did some research and it looks like it is indented behaviour in Qt - it doesn't set Basic authentication header is both user and password are empty.

**Comment by dawez** [comment]
I just disable the auth in my Transmission remote config.
