### ISSUE TITLE
Tracker errors not shown in torrent status

### ISSUE THREAD

**Issue by antivirtel** [equeim/tremotesf2#44]
1. Operating system: Win10 64bit
2. Transmission Deamon: 3.00-1ubuntu1~20.04.1
3. tremotesf2: 1.10.0

Hi,

I'm on Transmission v3.00, tremotesf2 doesn't seem to show (all) the tracker errors on the torrent status, it still says it's "Seeding" while it's definitely not doing anything, as the tracker reports: "err: unregistered torrent". Can this be fixed please? (Copy of https://github.com/transmission-remote-gui/transgui/issues/1401 - I start to think it's a Transmission-daemon bug...)

Thanks!

**Comment by equeim** [comment]
Tremotesf shows torrents status based on what Transmission tells it over RPC protocol. If Transmission doesn't say that torrent's status is error, then Tremotesf won't show error. I'm not sure what will be correct behaviour in this case, so I think you should create Transmission issue on this one.
