### ISSUE TITLE
Errored status is always zero

### ISSUE THREAD

**Issue by dsh2dsh** [equeim/tremotesf2#462]
Hi,

I had one torrent file, which is reporting it couldn't register to torrent tracker, because it was removed from the torrent tracker. And this torrent file wasn't in `Errored` state. I mean in the left column I see `Errored (0)`.

**Comment by equeim** [comment]
Does it show with error status in official transmission-qt client or transmission-remote-gtk?

**Comment by dsh2dsh** [comment]
Yes, transmission gui client shows it with error status. That's how I know I need to re-download this torrent.

**Comment by equeim** [comment]
@dsh2dsh I did some research and apparently Transmission does not report an error for torrent in that case if torrent has multiple trackers: https://github.com/transmission/transmission/blob/1e16912ae4a20ca338cfe89c72418cd37eac0102/libtransmission/announcer.cc#L1031

I don't really want to mess with this logic on client side since this is a deliberate behaviour on Transmission's part.

**Comment by dsh2dsh** [comment]
@equeim  oh sorry, I mean https://github.com/transmission-remote-gui/transgui
It reports an error for torrents not registered on it's tracker.

> if torrent has multiple trackers

I didn't tell anything about multiple trackers. My torrents has one tracker.

The goal is to know a torrent was replaced on a tracker. Without it how could I know I must re-download it.

**Comment by equeim** [comment]
I just checked and for me Tremotesf shows an error for unregistered torrent with one tracker, with Transmission 4.0.6

**Comment by dsh2dsh** [comment]
Is it possible that's because every torrent has a LAN local tracker? Like this:

```
http://bt3.t-ru.org/ann
http://retracker.local/announce
```

From this example `retracker.local` doesn't exists, because I don't have any retracker in my LAN. An the GUI reports "Could not connect".

**Comment by equeim** [comment]
> Is it possible that's because every torrent has a LAN local tracker? Like this:
> 
> ```
> http://bt3.t-ru.org/ann
> http://retracker.local/announce
> ```
> 
> From this example `retracker.local` doesn't exists, because I don't have any retracker in my LAN. An the GUI reports "Could not connect".

Yes, there must only one tracker in the list.

**Comment by dsh2dsh** [comment]
> there must only one tracker in the list

I tried it and unfortunately it doesn't work. I removed `retracker.local` from all of my torrents and today one of torrents was re-uploaded on the tracker. `transgui` reports `Error (1)`, but `tremotesf` reports `Errored (0)`. See attached screenshots:

![Screenshot_20240823_143251](https://github.com/user-attachments/assets/893a10f4-f0f5-47c8-8c54-2cf8fa58d220)
![Screenshot_20240823_143133](https://github.com/user-attachments/assets/a1ad18b3-2c4d-4fc4-884e-9a3a235ae31c)

**Comment by equeim** [comment]
Could be that Transmission doesn't update the status flag of the torrent correctly. I have seen this when removing retracker.local tracker, Transmission would not report error status for torrent until the daemon is restarted. Does it fix itself for you after restarting Transmission?

**Comment by dsh2dsh** [comment]
Yes, after restarting transmission daemon tremotesf reports `Errored (1)` as expected.

I'd like to note, transgui reports not registered torrents even without transmission daemon restart.

**Comment by equeim** [comment]
Fixed in 2.7.0
