### ISSUE TITLE
kwayland-integration dependency is broken in openSUSE TW since KDE 6 arrived

### ISSUE THREAD

**Issue by KottV** [equeim/tremotesf2#468]
Hi!

Since 20240311 TW snapshot, this line couldn't be satisfied:
```
%if %{without qt6}
# Wayland plugin for KWindowSystem, needed at runtime for window activation to work on Wayland
# In KF6 it's not a plugin anymore so we need only for KF5
Requires: kwayland-integration
%endif
```
the correct name for TW (opensuse >= 1600) is `kwayland-integration6`

**Comment by equeim** [comment]
Thanks! Not sure why kwayland-integration6 exists since it's a KF5 thing and appears identical to kwayland-integration but whatever.

BTW next version will build with Qt 6 for openSUSE.
