### ISSUE TITLE
Issue with Directory Mapping: Only One Path Recognized for Downloads

### ISSUE THREAD

**Issue by toniexly** [equeim/tremotesf2#511]
I have two local directories mapped to different remote directories: S:/ is mapped to /volume1/transmission, and T:/ is mapped to /volume2/transmission2. However, it seems that only one of these mappings is recognized. Regardless of whether the files are in S:/XXXXXXX or T:/, all downloaded files are opened using the path from S:/, even when they are actually located in /volume2/transmission2.

**Comment by equeim** [comment]
Fixed in 2.7.0

**Comment by toniexly** [comment]
works great now. thanks.
