### ISSUE TITLE
Strings of translation missing in GUI - at least German

### ISSUE THREAD

**Issue by uDEV2019** [equeim/tremotesf2#523]
Inside tremotesf there are many translated strings that are not displayed.
Instead of german strings, it displays the english strings.
Transifex shows 100% for german.

Some examples...
![image](https://github.com/user-attachments/assets/d48c3540-a9bf-4775-b778-ab79af1d5679)

![image](https://github.com/user-attachments/assets/ef54e9f9-6289-4252-bf8e-2c754742fdc2)

![image](https://github.com/user-attachments/assets/39febdbb-0259-4607-a6cf-5b73d77b3f3d)

![image](https://github.com/user-attachments/assets/971f9990-59de-4d00-bc87-053c9cb883eb)

**Comment by equeim** [comment]
> Transifex shows 100% for german.

You are probably looking at the page for Android app, for desktop one translations are here: https://explore.transifex.com/equeim/tremotesf/

**Comment by uDEV2019** [comment]
Oh no, what a fault by me...
