### ISSUE TITLE
Preferences doesn't work on macOS

### ISSUE THREAD

**Issue by DerBunteBall** [equeim/tremotesf2#537]
As title says: It seems that Preferences doesn't work on macOS (in my case Somona 14.6.1).

When I click on Tremotesf -> Preferences nothing happens (no dialog opens).

Other Dialogs like Connection Manager working. Also connecting to servers works fine.

Someone else experiencing similiar problems?

Best Regards

**Comment by equeim** [comment]
Strange, I can't reproduce it on Air M1 with macOS 14.6.1

Do you use the latest version of tremotesf?

**Comment by DerBunteBall** [comment]
I had 2.6.3 installed.

Upgraded it now which solved the issue.

My macOS is running on an older Intel Mac. That would be the only difference. But I can't imagine that this was the reason. I guess somehow the binary or some application file got corrupted or so.
