### ISSUE TITLE
Select Files dialog is reopened after file selection

### ISSUE THREAD

**Issue by bassstorm** [equeim/tremotesf2#546]
With upgrade to 2.7.2, there's a regression issue wrt File Choose dialog.

Steps:
1. Click 'Add Torrent File'
2. See 'Select Files' dialog is opened
3. Choose a torrent file (just one) and click 'Open'
4. See 'Add Torrent File' dialog with the torrent details **and 'Select Files' dialog reopened again in background**

System details:
Tremotesf v2.7.2 on Debian 12, KDE, Flatpak

**Comment by bassstorm** [comment]
Also maybe related, occasionally (like one of a dozen) I get a "error adding torrent" popup, so no torrent added to the list but its file is deleted.

**Comment by equeim** [comment]
Should be fixed in 2.7.3

**Comment by bassstorm** [comment]
Confirmed as fixed. Cheers!
