### ISSUE TITLE
macOS - Behave more like a Mac App

### ISSUE THREAD

**Issue by DerBunteBall** [equeim/tremotesf2#547]
On macOS the App behaves not really Mac like. Aspecially things like closing in Workspace mode doesn't work correctly (don't show/close really). Actually closing the app once works more or less (some strange blanking also happens) but doing the same thing again clears the workspace and give a blanked black ghost workspace. Normally the app shuold work further, the workspace is out of "scroll list" and view (hidden) and can be restored by clicking the App in Dock or a top icon. The workspace may never be blanked to a black screen. That's really a bug.

Version: 2.7.2
macOS Sonoma 14.7 - x86_64

**Comment by equeim** [comment]
Well the idea was that if tray icon (in top bar) is enabled then Tremotesf continues to work in background and its window can be reopened from dock or tray icon. If tray icon is disabled then closing the window exits the app.

I'm not a regular Mac user, do you mean it doesn't work correctly with its Spaces feature?

**Comment by DerBunteBall** [comment]
It's possible that the correct word is a space.

In fact it's full screen mode (Function key + F).

**Comment by equeim** [comment]
Should be fixed in 2.7.3

**Comment by DerBunteBall** [comment]
Fixed with the last version.

Fun fact: Whatever was changed also seems to have made the translations work on macOS.

Since the latest version, the app correctly adopts the system language and does not remain in English
