### ISSUE TITLE
My system language is English but the app runs in Spanish and nowhere in settings to modify it?

### ISSUE THREAD

**Issue by malcolmxtc** [equeim/tremotesf2#554]
Pretty much what the title says:

My system language is English but the app runs in Spanish and nowhere in settings to modify it.

Running 2.7.2 on Windows 10

Thanks!

**Comment by mikulik86** [comment]
After update to 2.7.3, my app switched to German.

**Comment by DerBunteBall** [comment]
That's wild.....

On macOS 2.7.3 took the system language while before it was always english.

@mikulik86: Is your system language German? My system language is German so if yours is not it might be the same thing on macOS isntead.

Best REgards

**Comment by equeim** [comment]
@solonix What's your Language & region Windows settings?

**Comment by equeim** [comment]
Looks like a bug in Qt: https://bugreports.qt.io/browse/QTBUG-129434

I will see if I can apply a workaround.

**Comment by equeim** [comment]
@malcolmxtc @mikulik86 @solonix Does this build fix the issue for you: https://github.com/equeim/tremotesf2/actions/runs/12146896469/artifacts/2269845270 ?

**Comment by solonix** [comment]
@equeim Error on start. Miss dll
![Снимок экрана 2024-12-04 071452](https://github.com/user-attachments/assets/3dee39c7-d788-4b87-baef-9e4a4044d356)

**Comment by equeim** [comment]
Sorry, here is working (hopefully) build: https://github.com/equeim/tremotesf2/actions/runs/12166710380/artifacts/2275453461

**Comment by solonix** [comment]
> Sorry, here is working (hopefully) build: https://github.com/equeim/tremotesf2/actions/runs/12166710380/artifacts/2275453461

Everything works fine. language switched back to Russian.

**Comment by DerBunteBall** [comment]
2.7.4 as normally flipped back to English on German macOS for me.
